# Generated by Django 3.2.23 on 2024-02-03 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20240203_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='last_poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='last_choice', to='polls.poll', verbose_name='Если вариант отвечает на вопрос'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='polls.poll'),
        ),
    ]
