# Generated by Django 3.2.23 on 2024-02-03 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20240203_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='last_poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_choice', to='polls.poll', verbose_name='Если вариант отвечает на вопрос'),
        ),
    ]
