# Generated by Django 3.2.23 on 2024-02-03 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_question_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='last_poll',
        ),
    ]
