# Generated by Django 3.2.23 on 2024-02-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_choice_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='question',
            name='poll',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
