# Generated by Django 3.2.23 on 2024-02-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(to='polls.Choice', verbose_name='Варианты ответа'),
        ),
    ]
