# Generated by Django 3.2.23 on 2024-02-03 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20240203_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_choices', to='polls.question', verbose_name='Следующий вопрос'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.question', verbose_name='Вариант ответа'),
        ),
    ]
