# Generated by Django 4.2.6 on 2024-02-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_poll_count_passes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='count_passes',
            field=models.IntegerField(default=0, verbose_name='Количество проходов'),
        ),
    ]
