# Generated by Django 4.2.6 on 2024-02-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_question_count_passes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='count_passes',
        ),
    ]
