# Generated by Django 4.2.6 on 2024-02-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_userresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='user',
            field=models.CharField(blank=True, default='Anonymous', max_length=200, null=True, verbose_name='Пользователь, ответивший на опрос'),
        ),
    ]
