# Generated by Django 3.2.23 on 2024-02-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_alter_userresponse_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='numbering',
            field=models.IntegerField(default=0, verbose_name='Нумерация'),
        ),
    ]
